quarkus:
  datasource:
    db-kind: h2
    jdbc:
      url: jdbc:h2:mem:test
    username: sa
    password: sa
  hibernate-orm:
    database:
      generation: drop-and-create
    log:
      sql: true
